### ISSUE TITLE
Inconsistencies in contribution list, exiting

### ISSUE THREAD

**Issue by alessia677** [a-xavier/tapes#15]
Hi! I am trying to run TAPES:

python3 tapes.py sort -i sample_1.vcf  --o ${name}_tapes/ --acmg -a hg38 --threads $nt --tab

But I got this output:

       ***TAPES: SORT***
        
2021-09-23 22:36:23.....Output type: FOLDER
2021-09-23 22:36:24.....annovar annotated file
2021-09-23 22:36:24.....Gene annotation : refGene
|| No sample data found
2021-09-23 22:36:24.....All required annotations found...
2021-09-23 22:36:24.....Loading databases... Done
2021-09-23 22:37:02.....Starting...
2021-09-23 22:37:02.....PVS1 done
2021-09-23 22:37:02.....PS1 done
|| No trio data, skipping PS2
2021-09-23 22:37:02.....PS3 done
2021-09-23 22:37:02.....PS4 done
2021-09-23 22:37:02.....PM1 done
2021-09-23 22:37:02.....PM2 done
2021-09-23 22:37:02.....PM4 and BP3 done
2021-09-23 22:37:02.....PM5 done
2021-09-23 22:37:02.....PP2 done
2021-09-23 22:37:02.....PP5 done
2021-09-23 22:37:02.....PP3 and BP4 done
2021-09-23 22:37:02.....BA1 done
2021-09-23 22:37:02.....BS1 done
2021-09-23 22:37:02.....BS2 done
2021-09-23 22:37:02.....BS3 done
2021-09-23 22:37:02.....BP1 done
2021-09-23 22:37:02.....BP6 done
2021-09-23 22:37:02.....BP7 done
2021-09-23 22:37:02.....ACMG Criteria assigned
Inconsistencies in contribution list, exiting
2021-09-23 22:37:10.....Starting...
2021-09-23 22:37:10.....PVS1 done
2021-09-23 22:37:10.....PS1 done
|| No trio data, skipping PS2
2021-09-23 22:37:10.....PS3 done
2021-09-23 22:37:10.....PS4 done
2021-09-23 22:37:10.....PM1 done
2021-09-23 22:37:10.....PM2 done
2021-09-23 22:37:10.....PM4 and BP3 done
2021-09-23 22:37:10.....PM5 done
2021-09-23 22:37:10.....PP2 done
2021-09-23 22:37:10.....PP5 done
2021-09-23 22:37:10.....PP3 and BP4 done
2021-09-23 22:37:10.....BA1 done
2021-09-23 22:37:10.....BS1 done
2021-09-23 22:37:10.....BS2 done
2021-09-23 22:37:10.....BS3 done
2021-09-23 22:37:10.....BP1 done
2021-09-23 22:37:10.....BP6 done
2021-09-23 22:37:10.....BP7 done
2021-09-23 22:37:10.....ACMG Criteria assigned
Inconsistencies in contribution list, exiting
2021-09-23 22:37:17.....Starting...
2021-09-23 22:37:17.....PVS1 done
2021-09-23 22:37:17.....PS1 done
|| No trio data, skipping PS2
2021-09-23 22:37:17.....PS3 done
2021-09-23 22:37:17.....PS4 done
2021-09-23 22:37:17.....PM1 done
2021-09-23 22:37:17.....PM2 done
2021-09-23 22:37:17.....PM4 and BP3 done
2021-09-23 22:37:17.....PM5 done
2021-09-23 22:37:17.....PP2 done
2021-09-23 22:37:17.....PP5 done
2021-09-23 22:37:17.....PP3 and BP4 done
2021-09-23 22:37:17.....BA1 done
2021-09-23 22:37:17.....BS1 done
2021-09-23 22:37:17.....BS2 done
2021-09-23 22:37:17.....BS3 done
2021-09-23 22:37:17.....BP1 done
2021-09-23 22:37:17.....BP6 done
2021-09-23 22:37:17.....BP7 done
2021-09-23 22:37:17.....ACMG Criteria assigned
Inconsistencies in contribution list, exiting
2021-09-23 22:37:25.....Starting...
2021-09-23 22:37:25.....PVS1 done
2021-09-23 22:37:25.....PS1 done
|| No trio data, skipping PS2
2021-09-23 22:37:25.....PS3 done
2021-09-23 22:37:25.....PS4 done
2021-09-23 22:37:25.....PM1 done
2021-09-23 22:37:25.....PM2 done
2021-09-23 22:37:25.....PM4 and BP3 done
2021-09-23 22:37:25.....PM5 done
2021-09-23 22:37:25.....PP2 done
2021-09-23 22:37:25.....PP5 done
2021-09-23 22:37:25.....PP3 and BP4 done
2021-09-23 22:37:25.....BA1 done
2021-09-23 22:37:25.....BS1 done
2021-09-23 22:37:25.....BS2 done
2021-09-23 22:37:25.....BS3 done
2021-09-23 22:37:25.....BP1 done
2021-09-23 22:37:25.....BP6 done
2021-09-23 22:37:25.....BP7 done
2021-09-23 22:37:25.....ACMG Criteria assigned
Inconsistencies in contribution list, exiting
2021-09-23 22:37:32.....Starting...
2021-09-23 22:37:32.....PVS1 done
2021-09-23 22:37:32.....PS1 done
|| No trio data, skipping PS2
2021-09-23 22:37:32.....PS3 done
2021-09-23 22:37:32.....PS4 done
2021-09-23 22:37:32.....PM1 done
2021-09-23 22:37:32.....PM2 done
2021-09-23 22:37:32.....PM4 and BP3 done
2021-09-23 22:37:32.....PM5 done
2021-09-23 22:37:32.....PP2 done
2021-09-23 22:37:32.....PP5 done
2021-09-23 22:37:32.....PP3 and BP4 done
2021-09-23 22:37:32.....BA1 done
2021-09-23 22:37:32.....BS1 done
2021-09-23 22:37:32.....BS2 done
2021-09-23 22:37:32.....BS3 done
2021-09-23 22:37:32.....BP1 done
2021-09-23 22:37:32.....BP6 done
2021-09-23 22:37:32.....BP7 done
2021-09-23 22:37:32.....ACMG Criteria assigned
Inconsistencies in contribution list, exiting
2021-09-23 22:37:39.....Starting...
2021-09-23 22:37:39.....PVS1 done
2021-09-23 22:37:39.....PS1 done
|| No trio data, skipping PS2
2021-09-23 22:37:39.....PS3 done
2021-09-23 22:37:39.....PS4 done
2021-09-23 22:37:39.....PM1 done
2021-09-23 22:37:39.....PM2 done
2021-09-23 22:37:39.....PM4 and BP3 done
2021-09-23 22:37:39.....PM5 done
2021-09-23 22:37:39.....PP2 done
2021-09-23 22:37:39.....PP5 done
2021-09-23 22:37:39.....PP3 and BP4 done
2021-09-23 22:37:39.....BA1 done
2021-09-23 22:37:39.....BS1 done
2021-09-23 22:37:39.....BS2 done
2021-09-23 22:37:39.....BS3 done
2021-09-23 22:37:39.....BP1 done
2021-09-23 22:37:39.....BP6 done
2021-09-23 22:37:39.....BP7 done
2021-09-23 22:37:39.....ACMG Criteria assigned
Inconsistencies in contribution list, exiting
2021-09-23 22:37:46.....Starting...
2021-09-23 22:37:46.....PVS1 done
2021-09-23 22:37:46.....PS1 done
|| No trio data, skipping PS2
2021-09-23 22:37:46.....PS3 done
2021-09-23 22:37:46.....PS4 done
2021-09-23 22:37:46.....PM1 done
2021-09-23 22:37:46.....PM2 done
2021-09-23 22:37:46.....PM4 and BP3 done
2021-09-23 22:37:46.....PM5 done
2021-09-23 22:37:46.....PP2 done
2021-09-23 22:37:46.....PP5 done
2021-09-23 22:37:46.....PP3 and BP4 done
2021-09-23 22:37:46.....BA1 done
2021-09-23 22:37:46.....BS1 done
2021-09-23 22:37:46.....BS2 done
2021-09-23 22:37:46.....BS3 done
2021-09-23 22:37:46.....BP1 done
2021-09-23 22:37:46.....BP6 done
2021-09-23 22:37:46.....BP7 done
2021-09-23 22:37:46.....ACMG Criteria assigned
Inconsistencies in contribution list, exiting
2021-09-23 22:37:53.....Starting...
2021-09-23 22:37:53.....PVS1 done
2021-09-23 22:37:53.....PS1 done
|| No trio data, skipping PS2
2021-09-23 22:37:53.....PS3 done
2021-09-23 22:37:53.....PS4 done
2021-09-23 22:37:53.....PM1 done
2021-09-23 22:37:53.....PM2 done
2021-09-23 22:37:53.....PM4 and BP3 done
2021-09-23 22:37:53.....PM5 done
2021-09-23 22:37:53.....PP2 done
2021-09-23 22:37:53.....PP5 done
2021-09-23 22:37:53.....PP3 and BP4 done
2021-09-23 22:37:53.....BA1 done
2021-09-23 22:37:53.....BS1 done
2021-09-23 22:37:53.....BS2 done
2021-09-23 22:37:53.....BS3 done
2021-09-23 22:37:53.....BP1 done
2021-09-23 22:37:53.....BP6 done
2021-09-23 22:37:53.....BP7 done
2021-09-23 22:37:53.....ACMG Criteria assigned
Inconsistencies in contribution list, exiting
2021-09-23 22:38:00.....Starting...
2021-09-23 22:38:00.....PVS1 done
2021-09-23 22:38:00.....PS1 done
|| No trio data, skipping PS2
2021-09-23 22:38:00.....PS3 done
2021-09-23 22:38:00.....PS4 done
2021-09-23 22:38:00.....PM1 done
2021-09-23 22:38:00.....PM2 done
2021-09-23 22:38:00.....PM4 and BP3 done
2021-09-23 22:38:00.....PM5 done
2021-09-23 22:38:00.....PP2 done
2021-09-23 22:38:00.....PP5 done
2021-09-23 22:38:00.....PP3 and BP4 done
2021-09-23 22:38:00.....BA1 done
2021-09-23 22:38:00.....BS1 done
2021-09-23 22:38:00.....BS2 done
2021-09-23 22:38:00.....BS3 done
2021-09-23 22:38:00.....BP1 done
2021-09-23 22:38:00.....BP6 done
2021-09-23 22:38:00.....BP7 done
2021-09-23 22:38:00.....ACMG Criteria assigned
Inconsistencies in contribution list, exiting
2021-09-23 22:38:08.....Starting...
2021-09-23 22:38:08.....PVS1 done
2021-09-23 22:38:08.....PS1 done
|| No trio data, skipping PS2
2021-09-23 22:38:08.....PS3 done
2021-09-23 22:38:08.....PS4 done
2021-09-23 22:38:08.....PM1 done
2021-09-23 22:38:08.....PM2 done
2021-09-23 22:38:08.....PM4 and BP3 done
2021-09-23 22:38:08.....PM5 done
2021-09-23 22:38:08.....PP2 done
2021-09-23 22:38:08.....PP5 done
2021-09-23 22:38:08.....PP3 and BP4 done
2021-09-23 22:38:08.....BA1 done
2021-09-23 22:38:08.....BS1 done
2021-09-23 22:38:08.....BS2 done
2021-09-23 22:38:08.....BS3 done
2021-09-23 22:38:08.....BP1 done
2021-09-23 22:38:08.....BP6 done
2021-09-23 22:38:08.....BP7 done
2021-09-23 22:38:08.....ACMG Criteria assigned
Inconsistencies in contribution list, exiting
2021-09-23 22:38:16.....Starting...
2021-09-23 22:38:16.....PVS1 done
2021-09-23 22:38:16.....PS1 done
|| No trio data, skipping PS2
2021-09-23 22:38:16.....PS3 done
2021-09-23 22:38:16.....PS4 done
2021-09-23 22:38:16.....PM1 done
2021-09-23 22:38:16.....PM2 done
2021-09-23 22:38:16.....PM4 and BP3 done
2021-09-23 22:38:16.....PM5 done
2021-09-23 22:38:16.....PP2 done
2021-09-23 22:38:16.....PP5 done
2021-09-23 22:38:16.....PP3 and BP4 done
2021-09-23 22:38:16.....BA1 done
2021-09-23 22:38:16.....BS1 done
2021-09-23 22:38:16.....BS2 done
2021-09-23 22:38:16.....BS3 done
2021-09-23 22:38:16.....BP1 done
2021-09-23 22:38:16.....BP6 done
2021-09-23 22:38:16.....BP7 done
2021-09-23 22:38:16.....ACMG Criteria assigned
Inconsistencies in contribution list, exiting
2021-09-23 22:38:24.....Starting...
2021-09-23 22:38:24.....PVS1 done
2021-09-23 22:38:24.....PS1 done
|| No trio data, skipping PS2
2021-09-23 22:38:24.....PS3 done
2021-09-23 22:38:24.....PS4 done
2021-09-23 22:38:24.....PM1 done
2021-09-23 22:38:24.....PM2 done
2021-09-23 22:38:24.....PM4 and BP3 done
2021-09-23 22:38:24.....PM5 done
2021-09-23 22:38:24.....PP2 done
2021-09-23 22:38:24.....PP5 done
2021-09-23 22:38:24.....PP3 and BP4 done
2021-09-23 22:38:24.....BA1 done
2021-09-23 22:38:24.....BS1 done
2021-09-23 22:38:24.....BS2 done
2021-09-23 22:38:24.....BS3 done
2021-09-23 22:38:24.....BP1 done
2021-09-23 22:38:24.....BP6 done
2021-09-23 22:38:24.....BP7 done
2021-09-23 22:38:24.....ACMG Criteria assigned
Inconsistencies in contribution list, exiting
2021-09-23 22:38:32.....Starting...
2021-09-23 22:38:32.....PVS1 done
2021-09-23 22:38:32.....PS1 done
|| No trio data, skipping PS2
2021-09-23 22:38:32.....PS3 done
2021-09-23 22:38:32.....PS4 done
2021-09-23 22:38:32.....PM1 done
2021-09-23 22:38:32.....PM2 done
2021-09-23 22:38:32.....PM4 and BP3 done
2021-09-23 22:38:32.....PM5 done
2021-09-23 22:38:32.....PP2 done
2021-09-23 22:38:32.....PP5 done
2021-09-23 22:38:32.....PP3 and BP4 done
2021-09-23 22:38:32.....BA1 done
2021-09-23 22:38:32.....BS1 done
2021-09-23 22:38:32.....BS2 done
2021-09-23 22:38:32.....BS3 done
2021-09-23 22:38:32.....BP1 done
2021-09-23 22:38:32.....BP6 done
2021-09-23 22:38:32.....BP7 done
2021-09-23 22:38:32.....ACMG Criteria assigned
Inconsistencies in contribution list, exiting
2021-09-23 22:38:40.....Starting...
2021-09-23 22:38:40.....PVS1 done
2021-09-23 22:38:40.....PS1 done
|| No trio data, skipping PS2
2021-09-23 22:38:40.....PS3 done
2021-09-23 22:38:40.....PS4 done
2021-09-23 22:38:40.....PM1 done
2021-09-23 22:38:40.....PM2 done
2021-09-23 22:38:40.....PM4 and BP3 done
2021-09-23 22:38:40.....PM5 done
2021-09-23 22:38:40.....PP2 done
2021-09-23 22:38:40.....PP5 done
2021-09-23 22:38:40.....PP3 and BP4 done
2021-09-23 22:38:40.....BA1 done
2021-09-23 22:38:40.....BS1 done
2021-09-23 22:38:40.....BS2 done
2021-09-23 22:38:40.....BS3 done
2021-09-23 22:38:40.....BP1 done
2021-09-23 22:38:40.....BP6 done
2021-09-23 22:38:40.....BP7 done
2021-09-23 22:38:40.....ACMG Criteria assigned
Inconsistencies in contribution list, exiting
2021-09-23 22:38:48.....Starting...
2021-09-23 22:38:48.....PVS1 done
2021-09-23 22:38:48.....PS1 done
|| No trio data, skipping PS2
2021-09-23 22:38:48.....PS3 done
2021-09-23 22:38:48.....PS4 done
2021-09-23 22:38:48.....PM1 done
2021-09-23 22:38:48.....PM2 done
2021-09-23 22:38:48.....PM4 and BP3 done
2021-09-23 22:38:48.....PM5 done
2021-09-23 22:38:48.....PP2 done
2021-09-23 22:38:48.....PP5 done
2021-09-23 22:38:48.....PP3 and BP4 done
2021-09-23 22:38:48.....BA1 done
2021-09-23 22:38:48.....BS1 done
2021-09-23 22:38:48.....BS2 done
2021-09-23 22:38:48.....BS3 done
2021-09-23 22:38:48.....BP1 done
2021-09-23 22:38:48.....BP6 done
2021-09-23 22:38:48.....BP7 done
2021-09-23 22:38:48.....ACMG Criteria assigned
Inconsistencies in contribution list, exiting

^CProcess ForkPoolWorker-27:
Process ForkPoolWorker-17:
Process ForkPoolWorker-25:
Process ForkPoolWorker-29:
Process ForkPoolWorker-20:
Process ForkPoolWorker-30:
Process ForkPoolWorker-18:
Process ForkPoolWorker-24:
Process ForkPoolWorker-19:
Process ForkPoolWorker-23:
Process ForkPoolWorker-28:
Process ForkPoolWorker-22:
Process ForkPoolWorker-26:
Process ForkPoolWorker-21:
Process ForkPoolWorker-16:
Traceback (most recent call last):
  tapes.py", line 357, in <module>
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 108, in worker

Any idea?

Thanks in advance

**Comment by MatteoSchiavinato** [comment]
Any solution to this? Going through the same issue.
