### ISSUE TITLE
TypeError: object of type 'int' has no len() 

### ISSUE THREAD

**Issue by NTNguyen13** [a-xavier/tapes#6]
Hi, I have run tapes annotate using annovar and acmg guideline succesfully, then I want to run tapes sort to get the result in tab format, however, when I run there's an error.

Command
```
python3 tapes.py annotate -i $vcf_file \
            -o ${vcf_file/vcf/tapes_annot} --acmg -a hg19
vcf_annot=${vcf_file/vcf/tapes_annot}        
python3 tapes.py sort -i ${vcf_annot/.vcf/.hg19_multianno.vcf} \
            -o ${vcf_annot/.vcf/.tsv} --tab
```
Error log (only tape sort shows problem)
        ***TAPES: SORT***
```
2020-05-07 10:01:12.....Output type: TXT/TSV + XLSX
2020-05-07 10:01:12.....Processing vcf... 2020-05-07 10:01:12.....Only one sample found in vcf
Done
2020-05-07 10:01:12.....annovar annotated file
2020-05-07 10:01:12.....Gene annotation : refGene
|| No sample data found
2020-05-07 10:01:12.....Loading databases... Done
2020-05-07 10:01:27.....Starting...
2020-05-07 10:01:27.....PVS1 done
2020-05-07 10:01:27.....PS1 done
|| No trio data, skipping PS2
2020-05-07 10:01:27.....PS3 done
2020-05-07 10:01:27.....PS4 done
2020-05-07 10:01:27.....PM1 done
2020-05-07 10:01:27.....PM2 done
2020-05-07 10:01:27.....PM4 and BP3 done
2020-05-07 10:01:27.....PM5 done
2020-05-07 10:01:27.....PP2 done
2020-05-07 10:01:27.....PP5 done
2020-05-07 10:01:27.....PP3 and BP4 done
2020-05-07 10:01:27.....BA1 done
2020-05-07 10:01:27.....BS1 done
2020-05-07 10:01:27.....BS2 done
2020-05-07 10:01:27.....BS3 done
2020-05-07 10:01:27.....BP1 done
2020-05-07 10:01:27.....BP6 done
2020-05-07 10:01:27.....BP7 done
2020-05-07 10:01:27.....ACMG Criteria assigned
Traceback (most recent call last):
  File "/home/nguyen/Exec/tapes/tapes.py", line 355, in <module>
    main()
  File "/home/nguyen/Exec/tapes/tapes.py", line 271, in main
    final_stuff = tf.process_data(full_stuff, ref_anno, number_of_samples, tup_databases, args.cutoff)
  File "/home/nguyen/Exec/tapes/src/t_func.py", line 2475, in process_data
    df_all = list_to_dataframe(all_criterias, names_list)
  File "/home/nguyen/Exec/tapes/src/t_func.py", line 1441, in list_to_dataframe
    if len(item) != scale:
TypeError: object of type 'int' has no len()
/path/to/sample.vcf

```

What have gone wrong in this case?

**Comment by rosaricla** [comment]
Any update in this error? I am having the same problem, it only happens with some samples but I can not find the cause.

**Comment by alessia677** [comment]
Have you solved it?
 I m facing the same issue

**Comment by px172** [comment]
Do you have 4 variants in the input file?
In my case,  src/vep_process.py  

if len(PS4_contrib) == 4:
(skip)
  PS4_contrib = PS4_contrib[0]

when PS4_contrib is passed to list_to_dataframe, it will raise  TypeError.  Our workaround is to change the number of input variants.
